[connections.vendor_fee_tracker]
type="sql"
dialect="sqlite3"
host=""
database=""
username=""
password=""

[connections.vendor_tracker]
type="sql"
dialect="sqlite3"
host=""
database=""
username=""
password=""
